[project]
authors = [
    {name = "Aran Garrod", email = "aran.garrod@gmail.com"},
]
dependencies = [
    "pandas>=2.2.3",
    "numpy>=2.2.2",
    "biopython>=1.85",
]
name = "kmer_gen"
requires-python = ">=3.10,<3.13"
version = "0.0.0"
description = "Simple repo to build kmers from fasta file sequences."
readme = "README.md"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["kmer_gen"]